### ISSUE TITLE
Handle the Events about sandbox container from containerd 

### ISSUE THREAD

**Issue by miaoyq** [kubernetes-incubator/cri-containerd#173]
Now we only handle the events about app container, I think we should handle the events about the sandbox container as well.

**Comment by Random-Liu** [comment]
@miaoyq We don't handle events for sandbox container, because we don't need to maintain its state inside cri-containerd.

We purely rely on the existence of the corresponding containerd task: if it's running, sandbox container is ready; if not, then not ready. So every time `PodSandboxStatus` is called, we get real time information from containerd, and generate the sandbox status.

That's why we don't maintain the state of the sandbox container, and that's also why we don't care about its event.

**Comment by miaoyq** [comment]
@Random-Liu  I understand, Thanks! : )
We should exclude the event sandbox containers from event stream in order to avoid outputting unexpected error print.

**Comment by Random-Liu** [comment]
Close this one since #177 is merged.
