### ISSUE TITLE
Invalid invocation of nsenter without netns for GetPodNetworkStatus

### ISSUE THREAD

**Issue by ijc** [kubernetes-incubator/cri-containerd#245]
I was doing some `strace` based debugging and spotted:
```
execve("/usr/bin/nsenter", ["/usr/bin/nsenter", "--net=", "-F", "--", "ip", "-o", "-4", "addr", "show", "dev", "eth0", "scope", "global"], [/* 2 vars */]) = 0
```
Which is invalid syntax due to the lack of the net arguments string option:
```
$ nsenter --net= -F -- echo foo
nsenter: cannot open : No such file or directory
```
And with sufficient logging enabled I see this in the `cri-containerd` logs too:
```
I0914 10:49:54.859715     564 sandbox_status.go:73] GetPodNetworkStatus returns error: Unexpected command output nsenter: cannot open : No such file or directory
 with error: exit status 1
```

Note that I do also see correct invocations of the form:
```
/usr/bin/nsenter --net=/var/run/netns/cni-5e8acebe-810d-c1b9-ced0-47be2f312fa8 -F -- <ip commandline>
```

This seems to come from [`criContainerdService.PodSandboxStatus`](https://github.com/kubernetes-incubator/cri-containerd/blob/master/pkg/server/sandbox_status.go#L62...L74).

I suspect it might be due to containers using the host netns?

I'm unsure if the issue is that `sandbox.NetNSPath` is wrong/missing in the first place or if instead the code should be conditional and simply skip this code if there is no `NetNSPath` (hence this is an issue rather than a PR, given some guidance on the expected behaviour I can make a PR though).

**Comment by Random-Liu** [comment]
@ijc 
For pod which is not using host network, after the sandbox is tore down, the network namespace will be gone. If we try to get pod status at that time, we'll see this. It should not be an error.

For pod which is using host network, CRI doesn't expect us to return a IP, because K8s will pick a proper host IP for us.

We should:
1) If pod is using host network, return empty ip;
2) else If network plugin status is not ready, return empty ip;
3) else If `GetNetworkStatus` returns error, log with lower log level, and return empty ip;
4) else return the correct ip.

**Comment by Random-Liu** [comment]
Probably add a `getIP` function in sandbox_status.go, and we also need some unit test for it.

Please also take a look at dockershim's implementation today. https://github.com/kubernetes/kubernetes/blob/4d409a4d9e9772193cb24944bd76b90aaca01473/pkg/kubelet/dockershim/docker_sandbox.go#L307-L345

**Comment by Random-Liu** [comment]
@ijc Have you got a chance to look at this? If not, I could fix this.

**Comment by ijc** [comment]
Not yet, I was hoping to have a look today (BST). I'll let you know at end of my (start of your) day if I do or not.

**Comment by ijc** [comment]
I took a stab at it in #262.

**Comment by Random-Liu** [comment]
@ijc Thanks! Will take a look.
