### ISSUE TITLE
Sandbox config - rlimit

### ISSUE THREAD

**Issue by DefunctExodus** [kubernetes-incubator/cri-containerd#515]
I am currently in the midst of configuring a cluster with `cri-contianerd` and I am struggling with the default rlimits that are passed down.
```
 "rlimits": [
          {
            "type": "RLIMIT_NOFILE",
            "hard": 1024,
            "soft": 1024
          }
     ],
```

I am wondering if there is a method to configure the rlimits.

Thanks

**Comment by Random-Liu** [comment]
@DefunctExodus Thanks for reporting this issue!

@crosbymichael I think the problem is that:
* Docker default OCI spec doesn't have rlimit: https://github.com/moby/moby/blob/master/oci/defaults.go#L57.
* Containerd default has that: https://github.com/containerd/containerd/blob/master/oci/spec_unix.go#L87.

Kubernetes doesn't have rlimit support today https://github.com/kubernetes/kubernetes/issues/3595, so it's using the Docker default. We should avoid regression for user switching from Docker to containerd. @crosbymichael Do you think we should remove this from containerd default, or should cri-containerd do that? Maybe cri-containerd should use `docker/oci.DefaultLinuxSpec()`?

**Comment by Random-Liu** [comment]
@DefunctExodus I discussed with @crosbymichael. To avoid regression, we'll remove the rlimit from the default spec for now.

However, please note that it means all your processes will inherit the limit from containerd. https://github.com/kubernetes-incubator/cri-containerd/blob/master/contrib/systemd-units/containerd.service#L14-L18
This is also the case for the Kubernetes Docker integration today.

**Comment by mikebrow** [comment]
So really two issues, one is the regression when moving from cri docker, the other is the CRI issue for specifying OCI runtime spec rlimits.

**Comment by DefunctExodus** [comment]
@Random-Liu 

Thanks for looking into this so quickly, that fix sounds just fine.

**Comment by Random-Liu** [comment]
@mikebrow Yeah, the rlimit issue for Kubernetes is tracked in kubernetes/kubernetes#3595.
